name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: arjs-gps # The folder the action should deploy.
