name: Deploy AFrame and ARjs to Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm
          cache-dependency-path: "./package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build -- --base=/${{ github.event.repository.name }}/
      - name: Deploy to GithubPages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          token: ${{ secrets.GITHUB_TOKEN }}
